### ISSUE TITLE
hwid changes every time app open

### ISSUE THREAD

**Issue by iTarek** [Pushwoosh/pushwoosh-ios-sdk#34]
With last version 4.0.8 hwid changes every time app open,  also users who installed our last version with latest sdk they do not get push notification.

**Comment by DimanAM** [comment]
Hwid may change periodically for debug builds (store applications should not be affected). And even if it changes it should not affect push notifications since only your push certificate and device push token are used to deliver pushes. Could you please provide more detailed information including device logs, iOS version and push "Message ID" from "Push History" in control panel?

**Comment by iTarek** [comment]
It affects deliver pushes if  Hwid changed since the last version because we are using tags to send to users who are subscribing on certain channels...

Are you now changing the Hwid every time we upload new version to appstore? Do we have to send tags with every new version?

**Comment by iTarek** [comment]
Trust me the last version is changing the Hwid in very strange and random way even on our testflight version, and this affects sending push with tags on mind. I guess I will not release with this last version I will use 4.0.7 till you fix this problem.

**Comment by DimanAM** [comment]
It is actually TestFlight "feature" http://stackoverflow.com/questions/26648840/ios-testflight-beta-app-get-new-advertising-identifier-in-each-run.
Production builds sould not be affected.

**Comment by shaders** [comment]
Added to the iOS FAQ http://docs.pushwoosh.com/docs/ios-faq#hwid-is-changing-every-times-app-open-when-install
