### ISSUE TITLE
Carthage (following)

### ISSUE THREAD

**Issue by frederic-c-dcode** [Pushwoosh/pushwoosh-ios-sdk#80]
_Originally posted by @frederic-c-dcode in https://github.com/Pushwoosh/pushwoosh-ios-sdk/issues/77#issuecomment-486122660_

Sorry for the delay. I had time to check again. When doing `carthage update`, it still says :
```
*** Skipped building pushwoosh-ios-sdk due to the error:
Dependency "pushwoosh-ios-sdk" has no shared framework schemes for any of the platforms: iOS

If you believe this to be an error, please file an issue with the maintainers at https://github.com/Pushwoosh/pushwoosh-ios-sdk/issues/new
```

I know you dont provide the source code to compile, but there should be a way to tell so in your carthage configuration ?

**Comment by wfhm** [comment]
@frederic-c-dcode 

Could you please provide the following information?

* Carthage version
* your cartfile contents
* the Terminal command you run

**Comment by frederic-c-dcode** [comment]
• Carthage version : 0.33.0
• Cartfile content : `github "Pushwoosh/pushwoosh-ios-sdk"` + all other dependencies outside Pushwoosh
• Terminal command : `carthage update --platform ios --no-use-binaries` (please note that --no-use-binaries is required for all other dependencies)

**Comment by wfhm** [comment]
@frederic-c-dcode

It seems that build fails exactly due to the `--no-use-binaries` flag. This flag tells Carthage not to use frameworks that have already been built but to try building them again using the sources if any. The thing is that the Pushwoosh SDK do not have sources on GitHub and as a result - the build fails.  In view of this, it is necessary to remove this flag to build your project correctly with the Pushwoosh SDK.
